AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false


Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 120
